SHOW DATABASES;
USE COMPANY_ATT0;
-- EXPRESSÕES E CONCATENAÇÃO DE STRINGS
-- RECUPERANDO INFORMAÇÕES DOS DEPARTAMENTOS PRESENTES EM STAFFORD
DESC DEP_LOCATIONS;
SHOW TABLES;
SELECT * FROM DEPARTAMENT;
SELECT * FROM WORKS_ON;
SELECT * FROM DEP_LOCATIONS; 
SELECT DNAME AS DEPARTAMENT_NAME, MGR_SSN AS MANAGER FROM DEPARTAMENT D, DEP_LOCATIONS L, EMPLOYEE E
	WHERE D.DNUMBER = L.DNUMBER AND DLOCATION = 'HOUSTON';
    
SELECT * FROM DEPARTAMENT D, DEP_LOCATIONS L, EMPLOYEE E
	WHERE D.DNUMBER = L.DNUMBER AND DLOCATION = 'HOUSTON';
 
 SELECT DNAME AS DEPARTAMENT_NAME, MGR_SSN AS MANAGER FROM DEPARTAMENT D, DEP_LOCATIONS L, EMPLOYEE E
	WHERE D.DNUMBER = L.DNUMBER AND DLOCATION = 'HOUSTON' AND MGR_SSN = E.SSN;
    
-- RECUPERANDO TODOS OS GERENTES, DEPARTAMENTOS E SEUS NOMES QUE TRABALHAM EM HOUSTON
    SELECT DNAME AS DEPARTAMENT_NAME, CONCAT(FNAME,' ',LNAME) AS MANAGER FROM DEPARTAMENT D, DEP_LOCATIONS L, EMPLOYEE E
	WHERE D.DNUMBER = L.DNUMBER AND DLOCATION = 'HOUSTON' AND MGR_SSN = E.SSN;

DESC PROJECT;
SELECT * FROM PROJECT;

    SELECT PNUMBER, DNUM, LNAME, ADDRESS, BDATE, P.PLOCATION FROM DEPARTAMENT D, PROJECT P, EMPLOYEE E
	WHERE D.DNUMBER = P.DNUM AND P.PLOCATION = 'BELLAIRE' AND MGR_SSN = E.SSN;