show databases;
use company_att0;
show tables;
SELECT * FROM EMPLOYEE;
-- GERENTE E SEU DEPARTAMENTO
select SSN, FNAME, DNAME FROM EMPLOYEE E, DEPARTAMENT D WHERE (E.SSN = D.MGR_SSN);

select FNAME, DEPENDENT_NAME, RELATIONSHIP FROM EMPLOYEE, DEPENDENT WHERE ESSN = SSN; 
select BDATE, ADDRESS FROM EMPLOYEE WHERE FNAME = 'JHON' AND MINIT='B' AND LNAME = 'SMITH';
-- RECUPERANDO DEPARTAMENTO ESPECÍFICO
SELECT * FROM DEPARTAMENT WHERE DNAME = 'RESEACH';

SELECT FNAME, LNAME, ADDRESS FROM  EMPLOYEE, DEPARTAMENT
	WHERE  DNAME = 'RESEACH' AND DNUMBER = DNO;
    
SELECT * FROM PROJECT;

SELECT PNAME, ESSN, FNAME, HOURS FROM PROJECT, WORKS_ON, EMPLOYEE WHERE PNUMBER = PNO AND ESSN = SSN;
desc employee;
desc departament;
desc DEP_LOCATIONS;
SELECT * FROM DEPARTAMENT;
SELECT D.DNUMBER, L.DNUMBER FROM DEPARTAMENT AS D, DEP_LOCATIONS AS L;
-- RETIRA A AMBIGUIDADE ATRAVÉS DO ALIAS OU AS STATEMENT
SELECT DNAME, L.DLOCATION AS DEPARTAMENT_NAME FROM DEPARTAMENT AS D, DEP_LOCATIONS AS L WHERE D.DNUMBER = L.DNUMBER;

SELECT CONCAT(FNAME, ' ', LNAME) FROM EMPLOYEE;